#!/usr/bin/env node
//
// gen-entry.js
//
// Generate api/_entry.js — the bundle's startup file. The entry exposes a
// REGISTRY of lazy service factories (build-time list of what's includable)
// and decides at runtime which to actually load based on SOLO_SERVICES_JSON.
//
// Why lazy factories: esbuild requires all require() calls to use static
// paths so it can resolve modules at build time. With factories, every service
// in services.json is bundled into solo.js, but only services listed in the
// consumer's SOLO_SERVICES_JSON are actually instantiated at runtime.
//
// Why a global port map: each service's config.js calls
// `library/ports.js → portFor(name, fallback)` which reads global.__SOLO_PORTS__.
// The entry sets this global BEFORE invoking any service factory.
//
// Usage:
//   node gen-entry.js <services.json> <output-entry.js>
//
// services.json shape: [{ name, path, port? }]   (port is optional, only used
// as a default if SOLO_SERVICES_JSON omits the entry).
//

const fs = require('fs');
const path = require('path');

const [servicesJson, outputFile] = process.argv.slice(2);
if (!servicesJson || !outputFile) {
    console.error('Usage: gen-entry.js <services.json> <output-entry.js>');
    process.exit(1);
}

const services = JSON.parse(fs.readFileSync(servicesJson, 'utf8'));

const factoryLines = services
    .map(s => `  '${s.name}': () => require('./${s.path}'),`)
    .join('\n');

// Embed each service's GUIDE.md at build time (fleet-standard `guide` method).
// esbuild loads .md as empty (--loader:.md=empty), so bundled services cannot
// fs-read their own GUIDE.md — library/guide.js reads global.__SOLO_GUIDES__
// first, mirroring the __SOLO_PORTS__ pattern. Services without a GUIDE.md are
// simply omitted (guide reports { available: false } at runtime).
const apiDir = path.dirname(path.resolve(outputFile));
const guideLines = services
    .map(s => {
        const guidePath = path.join(apiDir, path.dirname(s.path), 'GUIDE.md');
        if (!fs.existsSync(guidePath)) return null;
        return `  '${s.name}': ${JSON.stringify(fs.readFileSync(guidePath, 'utf8'))},`;
    })
    .filter(Boolean)
    .join('\n');

// Map of built-in defaults — used when SOLO_SERVICES_JSON is unset (single
// canonical bundle running with its built-in port set, e.g. for Solo dev mode).
const defaultsLines = services
    .filter(s => s.port != null)
    .map(s => `  { name: '${s.name}', port: ${s.port} },`)
    .join('\n');

const entry = `// Generated by deploy/gen-entry.js — do not edit.
const fs = require('fs');

const REGISTRY = {
${factoryLines}
};

const BUILT_IN_DEFAULTS = [
${defaultsLines}
];

// Build-time embedded GUIDE.md contents (fleet-standard \`guide\` method).
// Read by api/library/guide.js before falling back to fs (which is empty in
// the bundle — esbuild --loader:.md=empty).
global.__SOLO_GUIDES__ = {
${guideLines}
};

let cfg;
if (process.env.SOLO_SERVICES_JSON) {
  try {
    cfg = JSON.parse(fs.readFileSync(process.env.SOLO_SERVICES_JSON, 'utf8'));
  } catch (e) {
    console.error('[solo] failed to read SOLO_SERVICES_JSON at ' + process.env.SOLO_SERVICES_JSON + ': ' + e.message);
    process.exit(1);
  }
} else {
  console.warn('[solo] SOLO_SERVICES_JSON not set — starting all bundled services with built-in default ports');
  cfg = BUILT_IN_DEFAULTS;
}

// Populate port map BEFORE any service is required. Each config.js, when
// loaded by its factory below, will read global.__SOLO_PORTS__ via
// library/ports.js.
global.__SOLO_PORTS__ = Object.fromEntries(
  cfg.filter(s => s.port != null).map(s => [s.name, Number(s.port)])
);

for (const s of cfg) {
  const factory = REGISTRY[s.name];
  if (!factory) {
    console.error('[solo] unknown service in SOLO_SERVICES_JSON: ' + s.name);
    process.exit(1);
  }
  factory();
}
`;

fs.writeFileSync(outputFile, entry);
console.log(`  entry generated: ${outputFile} (${services.length} service${services.length === 1 ? '' : 's'} in REGISTRY)`);
