#!/usr/bin/env node
//
// gen-entry.js
//
// Generate api/_entry.js — the bundle's startup file. The entry exposes a
// REGISTRY of lazy service factories (build-time list of what's includable)
// and decides at runtime which to actually load based on SOLO_SERVICES_JSON.
//
// Why lazy factories: esbuild requires all require() calls to use static
// paths so it can resolve modules at build time. With factories, every service
// in services.json is bundled into solo.js, but only services listed in the
// consumer's SOLO_SERVICES_JSON are actually instantiated at runtime.
//
// The generated entry exports { REGISTRY, BUILT_IN_DEFAULTS, start } and only
// auto-starts when the bundle IS the process entry (node solo.js). require()ing
// it is side-effect free, and SOLO_SERVICES_JSON unset REFUSES to start
// (SOLO_START_ALL=1 explicitly opts into all-services-on-default-ports).
// Background: docs/feedback/done/bundle-require-boots-full-fleet.md
//
// Why a global port map: each service's config.js calls
// `library/ports.js → portFor(name, fallback)` which reads global.__SOLO_PORTS__.
// The entry sets this global BEFORE invoking any service factory.
//
// Usage:
//   node gen-entry.js <services.json> <output-entry.js>
//
// services.json shape: [{ name, path, port? }]   (port is optional, only used
// as a default if SOLO_SERVICES_JSON omits the entry).
//

const fs = require('fs');
const path = require('path');

const [servicesJson, outputFile] = process.argv.slice(2);
if (!servicesJson || !outputFile) {
    console.error('Usage: gen-entry.js <services.json> <output-entry.js>');
    process.exit(1);
}

const services = JSON.parse(fs.readFileSync(servicesJson, 'utf8'));

const factoryLines = services
    .map(s => `  '${s.name}': () => require('./${s.path}'),`)
    .join('\n');

// Embed each service's GUIDE.md at build time (fleet-standard `guide` method).
// esbuild loads .md as empty (--loader:.md=empty), so bundled services cannot
// fs-read their own GUIDE.md — library/guide.js reads global.__SOLO_GUIDES__
// first, mirroring the __SOLO_PORTS__ pattern. Services without a GUIDE.md are
// simply omitted (guide reports { available: false } at runtime).
const apiDir = path.dirname(path.resolve(outputFile));
const guideLines = services
    .map(s => {
        const guidePath = path.join(apiDir, path.dirname(s.path), 'GUIDE.md');
        if (!fs.existsSync(guidePath)) return null;
        return `  '${s.name}': ${JSON.stringify(fs.readFileSync(guidePath, 'utf8'))},`;
    })
    .filter(Boolean)
    .join('\n');

// Map of built-in defaults — used when SOLO_SERVICES_JSON is unset (single
// canonical bundle running with its built-in port set, e.g. for Solo dev mode).
const defaultsLines = services
    .filter(s => s.port != null)
    .map(s => `  { name: '${s.name}', port: ${s.port} },`)
    .join('\n');

const entry = `// Generated by deploy/gen-entry.js — do not edit.
const fs = require('fs');

const REGISTRY = {
${factoryLines}
};

const BUILT_IN_DEFAULTS = [
${defaultsLines}
];

// Build-time embedded GUIDE.md contents (fleet-standard \`guide\` method).
// Read by api/library/guide.js before falling back to fs (which is empty in
// the bundle — esbuild --loader:.md=empty).
global.__SOLO_GUIDES__ = {
${guideLines}
};

function resolveConfig() {
  if (process.env.SOLO_SERVICES_JSON) {
    try {
      return JSON.parse(fs.readFileSync(process.env.SOLO_SERVICES_JSON, 'utf8'));
    } catch (e) {
      console.error('[solo] failed to read SOLO_SERVICES_JSON at ' + process.env.SOLO_SERVICES_JSON + ': ' + e.message);
      process.exit(1);
    }
  }
  // "Unset env → quietly boot the whole fleet on default ports" turned a debug
  // one-liner into a three-day shadow stack sharing a production Redis (see
  // docs/feedback/done/bundle-require-boots-full-fleet.md). Starting 14 listeners is
  // never an acceptable default; the dev convenience survives behind an
  // explicit opt-in.
  if (process.env.SOLO_START_ALL === '1') {
    console.warn('[solo] SOLO_START_ALL=1 — starting ALL bundled services on built-in default ports');
    return BUILT_IN_DEFAULTS;
  }
  console.error('[solo] SOLO_SERVICES_JSON not set — refusing to start.');
  console.error('[solo] Set SOLO_SERVICES_JSON=<path to services list> (deploy/run.sh does this),');
  console.error('[solo] or set SOLO_START_ALL=1 to explicitly start every bundled service on default ports.');
  process.exit(1);
}

function start() {
  const cfg = resolveConfig();

  // Populate port map BEFORE any service is required. Each config.js, when
  // loaded by its factory below, will read global.__SOLO_PORTS__ via
  // library/ports.js.
  global.__SOLO_PORTS__ = Object.fromEntries(
    cfg.filter(s => s.port != null).map(s => [s.name, Number(s.port)])
  );

  // The bundle is ONE process hosting MANY services. PORT and ROUTER_URL are
  // "single process, single identity" env vars — legitimate for a standalone
  // private-app process (run.sh's own private-app spawn sets them explicitly,
  // per-child), meaningless and dangerous here. 14 of this bundle's own
  // config.js files still read \`process.env.ROUTER_URL || urlFor('router', ...)\`
  // (the env wins) — a ROUTER_URL leaked from an earlier \`export\` in the same
  // shell, or from a differently-configured sibling Solo stack, silently
  // redirects every event this bundle emits to a FOREIGN Router. That Router
  // rejects it (unregistered source) and logs the rejection in ITS OWN project
  // — invisible here. A leaked PORT is worse: portFor() honors process.env.PORT
  // by design (a standalone process needs to pin its own listen port), so
  // every bundled service would try to bind the SAME port; only the first
  // one wins and the rest fail silently. Clearing both here — once, upstream
  // of every service's config.js — protects all of them without relying on
  // each one being written correctly, and without touching run.sh's private-app
  // spawn (a legitimately different, single-process consumer of these same names).
  // Background: docs/feedback/done/inherited-router-url-silent-misdelivery.md
  delete process.env.PORT;
  delete process.env.ROUTER_URL;

  // Bind-failure watchdog — MUST hook net.Server.listen, nothing higher up
  // catches this. Express 5's app.listen registers the success callback ALSO
  // as the server's error handler (application.js: \`server.once('error', done)\`),
  // so on EADDRINUSE the error is consumed (never reaches uncaughtException)
  // AND the service's callback runs anyway, logging "Service running on port
  // X" for a port it does not hold (verified against express 5.2.1: callback
  // fires, server.address() === null, zero errors anywhere). Observed on N100
  // as 13/14 services gone while every log line claimed success. Wrapping
  // listen() attaches our own error listener per server, before any factory
  // runs: a listen EADDRINUSE names the dead service loudly, and once more
  // than half the declared fleet failed to bind the process exits — a
  // majority-dead stack must not keep reporting for duty. Non-EADDRINUSE
  // server errors are re-thrown asynchronously when nobody else listens,
  // preserving today's crash/route-to-uncaughtException semantics.
  const portOwner = new Map(cfg.filter(s => s.port != null).map(s => [Number(s.port), s.name]));
  const bindFailed = new Set();
  const net = require('net');
  const realListen = net.Server.prototype.listen;
  net.Server.prototype.listen = function (...args) {
    this.once('error', (err) => {
      if (err && err.code === 'EADDRINUSE' && err.syscall === 'listen') {
        const name = portOwner.get(err.port) || ('port ' + err.port);
        bindFailed.add(name);
        console.error('[solo] BIND FAILED: service "' + name + '" could not listen on port ' + err.port +
          ' (EADDRINUSE) — another process holds it. The service is NOT running,' +
          ' even if its own log claims otherwise (express 5 fires the success callback on error).');
        console.error('[solo]   inspect: lsof -nP -iTCP:' + err.port + ' -sTCP:LISTEN');
        if (bindFailed.size * 2 > cfg.length) {
          console.error('[solo] ' + bindFailed.size + '/' + cfg.length + ' services failed to bind — more than half the fleet is dead, exiting.');
          process.exit(1);
        }
      } else if (this.listenerCount('error') === 0) {
        setImmediate(() => { throw err; });
      }
    });
    return realListen.apply(this, args);
  };

  for (const s of cfg) {
    const factory = REGISTRY[s.name];
    if (!factory) {
      console.error('[solo] unknown service in SOLO_SERVICES_JSON: ' + s.name);
      process.exit(1);
    }
    factory();
  }
}

module.exports = { REGISTRY, BUILT_IN_DEFAULTS, start };

// Auto-start ONLY when this bundle IS the process entry (\`node solo.js\`,
// which is how run.sh launches it). A require() — debug one-liner, REPL,
// introspection tooling — gets { REGISTRY, BUILT_IN_DEFAULTS, start } and NO
// side effects; requiring a module must never boot a fleet.
// Compared via require.main.filename, not \`require.main === module\`: esbuild
// wraps this CJS entry in a __commonJS closure whose \`module\` is an internal
// stub, while \`__filename\` still resolves to the emitted bundle file.
if (require.main && require.main.filename === __filename) start();
`;

fs.writeFileSync(outputFile, entry);
console.log(`  entry generated: ${outputFile} (${services.length} service${services.length === 1 ? '' : 's'} in REGISTRY)`);
