import { useState, useEffect, useMemo } from 'react';
import type { Workflow } from './types';
import { callRpc } from '../../../utils/rpc';
import { useUI } from '../../../providers/UIProvider';

interface CategoryItem {
  id: string;
  label: Record<string, string> | string;
  desc: string;
}

interface CategoryConfig {
  key: string;
  label: Record<string, string> | string;
  items: CategoryItem[];
}

interface WorkflowBasicSectionProps {
  workflow: Workflow;
  onUpdate: () => void;
  onEditStateChange?: (isEditing: boolean) => void;
}

export default function WorkflowBasicSection({ workflow, onUpdate, onEditStateChange }: WorkflowBasicSectionProps) {
  const { toast } = useUI();
  const [saving, setSaving] = useState(false);
  const [categoryItems, setCategoryItems] = useState<CategoryItem[]>([]);

  // Lock modal close on mount (Always Edit Mode - like PromptsSection)
  useEffect(() => {
    onEditStateChange?.(true);
    return () => onEditStateChange?.(false);
  }, [onEditStateChange]);


  // Local State
  const [localId, setLocalId] = useState('');
  const [localName, setLocalName] = useState('');
  const [localDesc, setLocalDesc] = useState('');
  const [localCategory, setLocalCategory] = useState<Record<string, string>>({});
  const [localTags, setLocalTags] = useState('');

  // Initialization
  useEffect(() => {
    setLocalId(workflow.id);
    setLocalName(workflow.name);
    setLocalDesc(workflow.desc || '');
    // Parse category - should be an object like { TYPE: "meeting" }
    let categoryObj: Record<string, string> = {};
    console.log('[BasicSection] Raw category:', workflow.category, 'type:', typeof workflow.category);
    
    if (typeof workflow.category === 'object' && workflow.category !== null) {
      // Could be { TYPE: "xxx" } or empty {}
      categoryObj = { ...workflow.category } as Record<string, string>;
    } else if (typeof workflow.category === 'string' && workflow.category) {
      try {
        const parsed = JSON.parse(workflow.category);
        if (typeof parsed === 'object' && parsed !== null) {
          categoryObj = parsed;
        } else {
          // Parsed to non-object (e.g., just a string), treat as TYPE value
          categoryObj = { TYPE: String(parsed) };
        }
      } catch {
        // Not valid JSON, treat as TYPE value directly
        categoryObj = { TYPE: workflow.category };
      }
    }
    
    console.log('[BasicSection] Parsed categoryObj:', categoryObj);
    setLocalCategory(categoryObj);
    setLocalTags(workflow.tags?.join(', ') || '');
  }, [workflow]);

  // Fetch category items
  useEffect(() => {
    const fetchCategories = async () => {
      try {
        const result = await callRpc<CategoryConfig[] | { categories: CategoryConfig[] }>('orchestrator.category.list', {});
        let catList: CategoryConfig[] = [];
        if (Array.isArray(result)) {
          catList = result;
        } else if (result && 'categories' in result && Array.isArray(result.categories)) {
          catList = result.categories;
        }
        // Find TYPE category (main workflow category)
        const typeCat = catList.find(c => c.key === 'TYPE');
        if (typeCat?.items) {
          setCategoryItems(typeCat.items);
        }
      } catch (e) {
        console.warn('Failed to load categories', e);
      }
    };
    fetchCategories();
  }, []);

  // Dirty Check
  const isDirty = useMemo(() => {
    const idChanged = localId !== workflow.id;
    const nameChanged = localName !== workflow.name;
    const descChanged = localDesc !== (workflow.desc || '');
    
    const currentCategoryStr = JSON.stringify(localCategory);
    const origCategoryStr = typeof workflow.category === 'object' 
      ? JSON.stringify(workflow.category) 
      : JSON.stringify({ TYPE: workflow.category });
    const categoryChanged = currentCategoryStr !== origCategoryStr;
    
    const currentTags = localTags.split(',').map(t => t.trim()).filter(Boolean).join(',');
    const origTags = (workflow.tags || []).join(',');
    const tagsChanged = currentTags !== origTags;

    return idChanged || nameChanged || descChanged || categoryChanged || tagsChanged;
  }, [localId, localName, localDesc, localCategory, localTags, workflow]);

  const formatDate = (ts: number) => {
    if (!ts) return '-';
    return new Date(ts).toLocaleString();
  };

  const handleSave = async () => {
    // ID validation removed as it is auto-generated by system
    // if (!localId.trim()) { ... }

    setSaving(true);
    try {
      const isNew = !workflow.id;
      const method = isNew ? 'orchestrator.workflow.create' : 'orchestrator.workflow.update';
      
      await callRpc(method, {
        ...(isNew ? {} : { id: localId }),
        name: localName,
        desc: localDesc,
        category: localCategory,
        tags: localTags.split(',').map(t => t.trim()).filter(Boolean),
        // Initialize other fields for create
        ...(isNew ? {
          priority: 0,
          steps: [],
          resolvers: {},
          keywords: []
        } : {})
      });
      toast.success(isNew ? 'Workflow created' : 'Basic info updated');
      onUpdate();
    } catch (e: any) {
      toast.error((!workflow.id ? 'Create' : 'Update') + ' failed: ' + e.message);
    } finally {
      setSaving(false);
    }
  };

  const getCategoryLabel = (item: CategoryItem) => {
    if (typeof item.label === 'object') {
      return item.label['en'] || item.label['zh'] || item.id;
    }
    return item.label || item.id;
  };

  // Find matching category item (case-insensitive)
  const rawTypeValue = localCategory['TYPE'] || '';
  const matchedItem = categoryItems.find(
    item => item.id.toLowerCase() === rawTypeValue.toLowerCase()
  );
  const currentTypeValue = matchedItem?.id || rawTypeValue;


  return (
    <div style={{ padding: '16px', background: 'rgba(0,0,0,0.1)' }}>
      {/* Toolbar */}
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: '16px' }}>
        <button 
          className="service-btn small success"
          onClick={handleSave}
          disabled={!isDirty || saving}
          style={{ 
            opacity: isDirty ? 1 : 0.3, 
            pointerEvents: isDirty ? 'auto' : 'none',
            padding: '4px 16px',
            fontSize: '11px'
          }}
        >
          {saving ? 'SAVING...' : (!workflow.id ? 'CREATE' : 'UPDATE')}
        </button>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
        

        {/* ID (Editable only for new, otherwise Read-only) */}
        {/* ID - Hidden for new (auto-generated), shown as metadata for existing */}
        {workflow.id && (
           /* Only show explicitly if we want editable ID in future, otherwise it's in metadata footer */
           /* For now, we rely on the footer metadata for ID display */
           <div style={{ display: 'none' }}></div>
        )}

        {/* NAME */}
        <div>
          <div style={{ fontSize: '11px', fontWeight: 600, marginBottom: '8px', opacity: 0.7 }}>
            NAME
          </div>
          <input 
            type="text"
            value={localName}
            onChange={e => setLocalName(e.target.value)}
            placeholder="Workflow name..."
            style={{ 
              width: '100%', 
              background: '#1c2128', border: '1px solid #444', 
              color: 'white', fontSize: '12px', padding: '8px',
              borderRadius: '4px'
            }}
          />
        </div>

        {/* DESCRIPTION */}
        <div>
          <div style={{ fontSize: '11px', fontWeight: 600, marginBottom: '8px', opacity: 0.7 }}>
            DESCRIPTION
          </div>
          <textarea
            value={localDesc}
            onChange={e => setLocalDesc(e.target.value)}
            placeholder="Workflow description..."
            style={{ 
              width: '100%', minHeight: '80px', 
              background: '#1c2128', border: '1px solid #444', 
              color: 'white', fontSize: '12px', padding: '8px',
              fontFamily: 'inherit', borderRadius: '4px', resize: 'vertical'
            }}
          />
        </div>

        {/* CATEGORY & TAGS Row */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
          {/* CATEGORY */}
          <div>
            <div style={{ fontSize: '11px', fontWeight: 600, marginBottom: '8px', opacity: 0.7 }}>
              CATEGORY <span style={{opacity:0.5, fontWeight:400}}>(TYPE)</span>
            </div>
            <select
              value={currentTypeValue}
              onChange={e => setLocalCategory({ ...localCategory, TYPE: e.target.value })}
              style={{ 
                width: '100%', 
                background: '#1c2128', border: '1px solid #444', 
                color: 'white', fontSize: '12px', padding: '8px',
                borderRadius: '4px', cursor: 'pointer'
              }}
            >
              <option value="">-- Select Category --</option>
              {categoryItems.map(item => (
                <option key={item.id} value={item.id}>
                  {getCategoryLabel(item)}
                </option>
              ))}
            </select>
          </div>

          {/* TAGS */}
          <div>
            <div style={{ fontSize: '11px', fontWeight: 600, marginBottom: '8px', opacity: 0.7 }}>
              TAGS <span style={{opacity:0.5, fontWeight:400}}>(comma separated)</span>
            </div>
            <input 
              type="text"
              value={localTags}
              onChange={e => setLocalTags(e.target.value)}
              placeholder="tag1, tag2, ..."
              style={{ 
                width: '100%', 
                background: '#1c2128', border: '1px solid #444', 
                color: 'white', fontSize: '12px', padding: '8px',
                borderRadius: '4px'
              }}
            />
          </div>
        </div>

        {/* Read-only Info - subtle display */}
        <div style={{ 
          display: 'flex',
          gap: '24px',
          fontSize: '10px',
          opacity: 0.4,
          paddingTop: '8px',
          borderTop: '1px dashed #333'
        }}>
          {workflow.id && <span><span style={{ opacity: 0.6 }}>ID:</span> {workflow.id}</span>}
          <span><span style={{ opacity: 0.6 }}>Created:</span> {formatDate(workflow.createdAt)}</span>
          <span><span style={{ opacity: 0.6 }}>Updated:</span> {formatDate(workflow.updatedAt)}</span>
        </div>

      </div>
    </div>
  );
}
