/**
 * CI jest config — ALLOW-LIST of the suites verified to pass deterministically in
 * a clean box (Redis up, no external services, no API keys).
 *
 * Why an allow-list instead of an ignore-list: many files under tests/ are not
 * hermetic jest suites — some are standalone scripts (console.log + process.exit,
 * which jest flags as failures), some need the live mesh (Router:8600), external
 * LLM/vision APIs (core/agent/**), seeded Redis/seed.json state, RedisJSON/Search
 * modules, or on-disk WAL layout. Until those are made hermetic, the gate runs only the
 * proven-green subset so a red build always means a real regression.
 *
 * Verified green 2026-06-30 (105 suites / 1690 tests). To add a suite: make it pass
 * under `npx jest <file>` with Redis up and nothing else, then list it here.
 * sample/tests/* are the canonical hermetic examples (see api/sample/README.md#testing).
 *
 * NEXT (tracked in docs/planning/BACKLOG.md §5): triage the remaining excluded suites —
 * make the script-style "tests" real jest or move them out of the test glob, and stand up
 * a live-stack E2E job for e2e-permission / rbac-blackbox / *integration. (validator's
 * OOM-shield test was fixed + promoted into the gate 2026-06-30.)
 */
module.exports = {
    rootDir: '.',
    testMatch: [
        '<rootDir>/core/orchestrator/tests/engine.test.js',
        '<rootDir>/core/orchestrator/tests/trace-audit.test.js',
        '<rootDir>/core/notification/tests/worker.test.js',
        '<rootDir>/core/administrator/tests/handlers.test.js',
        '<rootDir>/core/user/tests/introspection.test.js',
        '<rootDir>/core/user/tests/bot-revoke.test.js',
        '<rootDir>/core/user/tests/bot-suspend.test.js',
        '<rootDir>/core/gateway/tests/webhook.test.js',
        '<rootDir>/core/user/tests/passport.test.js',
        '<rootDir>/core/user/tests/passport-otp.test.js',
        '<rootDir>/core/user/tests/role.test.js',
        '<rootDir>/core/user/tests/key.test.js',
        '<rootDir>/core/user/tests/returns-contract.test.js',
        '<rootDir>/apps/approval/tests/record.test.js',
        '<rootDir>/apps/approval/tests/gate.test.js',
        '<rootDir>/apps/approval/tests/returns-contract.test.js',
        '<rootDir>/apps/collection/tests/returns-contract.test.js',
        '<rootDir>/apps/collection/tests/logic.test.js',
        '<rootDir>/apps/fulfillment/tests/profile-lint.test.js',
        '<rootDir>/library/tests/risk.test.js',
        '<rootDir>/router/tests/auth.test.js',
        '<rootDir>/router/tests/tasks.test.js',
        '<rootDir>/router/tests/category_protocol.test.js',
        '<rootDir>/router/tests/service.test.js',
        '<rootDir>/router/tests/forward.test.js',
        '<rootDir>/router/tests/security/access.test.js',
        '<rootDir>/library/tests/permit.test.js',
        '<rootDir>/library/tests/auth-middleware.test.js',
        '<rootDir>/library/tests/auth-handshake.test.js',
        '<rootDir>/library/tests/fieldmask.test.js',
        '<rootDir>/library/tests/validate.test.js',
        '<rootDir>/library/tests/injection-detect.test.js',
        '<rootDir>/library/tests/contract.test.js',
        '<rootDir>/library/tests/generator.test.js',
        '<rootDir>/library/tests/crypto.test.js',
        '<rootDir>/library/tests/router-auth.test.js',
        '<rootDir>/library/tests/jsonrpc.test.js',
        '<rootDir>/library/tests/jsonlogic.test.js',
        '<rootDir>/library/tests/entity-list-order.test.js',
        '<rootDir>/library/tests/ports.test.js',
        '<rootDir>/library/tests/constants.test.js',
        '<rootDir>/library/tests/filestore.test.js',
        '<rootDir>/apps/storage/tests/oss-keying.test.js',
        '<rootDir>/apps/storage/tests/oss-provider.test.js',
        '<rootDir>/apps/storage/tests/asset-authz.test.js',
        '<rootDir>/apps/storage/tests/returns-contract.test.js',
        '<rootDir>/library/tests/optimistic.test.js',
        '<rootDir>/library/tests/entity-wal-stream.test.js',
        '<rootDir>/library/tests/walarchiver.test.js',
        '<rootDir>/library/tests/bootstrap.test.js',
        '<rootDir>/library/tests/logger-redact.test.js',
        '<rootDir>/library/tests/relay-callas.test.js',
        '<rootDir>/library/tests/health.test.js',
        // library 100%-coverage hardening (2026-06-28): new + promoted hermetic suites
        '<rootDir>/library/tests/clock.test.js',
        '<rootDir>/library/tests/passport.test.js',
        '<rootDir>/library/tests/config.test.js',
        '<rootDir>/library/tests/process.test.js',
        '<rootDir>/library/tests/indexer.test.js',
        '<rootDir>/library/tests/search.test.js',
        '<rootDir>/library/tests/vector.test.js',
        '<rootDir>/library/tests/relay.test.js',
        '<rootDir>/library/tests/category.test.js',
        '<rootDir>/library/tests/cors.test.js',
        '<rootDir>/library/tests/auth-coverage.test.js',
        '<rootDir>/library/tests/entity-coverage.test.js',
        '<rootDir>/library/tests/logger.test.js',
        '<rootDir>/library/tests/optimistic-coverage.test.js',
        '<rootDir>/library/tests/bootstrap.init.test.js',
        '<rootDir>/core/orchestrator/tests/footprint-precheck.test.js',
        '<rootDir>/core/orchestrator/tests/actor-precheck.test.js',
        '<rootDir>/core/orchestrator/tests/approval-gate.test.js',
        '<rootDir>/core/orchestrator/tests/condition.test.js',
        '<rootDir>/core/orchestrator/tests/trigger-gate.test.js',
        '<rootDir>/core/orchestrator/tests/worker.test.js',
        '<rootDir>/core/orchestrator/tests/human-in-loop.test.js',
        '<rootDir>/core/orchestrator/tests/matcher.test.js',
        '<rootDir>/core/orchestrator/tests/static-workflow-hardening.test.js',
        '<rootDir>/core/orchestrator/tests/layered-approval.test.js',
        '<rootDir>/core/orchestrator/tests/returns-contract.test.js',
        '<rootDir>/core/nexus/tests/scheduler.test.js',
        '<rootDir>/core/nexus/tests/context.test.js',
        '<rootDir>/core/nexus/tests/dlq.test.js',
        '<rootDir>/core/nexus/tests/stream.test.js',
        '<rootDir>/core/nexus/tests/sentinel.test.js',
        '<rootDir>/core/nexus/tests/identity.test.js',
        '<rootDir>/core/nexus/tests/control.test.js',
        '<rootDir>/core/nexus/tests/events.test.js',
        '<rootDir>/core/orchestrator/tests/control.test.js',
        '<rootDir>/core/agent/tests/mock-provider.test.js',
        '<rootDir>/core/agent/tests/decide.test.js',
        '<rootDir>/core/agent/tests/focus.test.js',
        '<rootDir>/core/agent/tests/model-config.test.js',
        '<rootDir>/router/tests/events.test.js',
        '<rootDir>/router/tests/trace.test.js',
        '<rootDir>/router/tests/ratelimit.test.js',
        // validator OOM-shield test fixed 2026-06-30 (pins MAX_STRING_LENGTH at require); promoted into the gate
        '<rootDir>/router/tests/validator.test.js',
        // 5.2 promotion 2026-06-30: hermetic-but-excluded suites verified green and added to the gate
        // (system/capability/identity were also reviewed but excluded — they fail or hang non-hermetically)
        '<rootDir>/core/orchestrator/tests/run.test.js',
        '<rootDir>/core/orchestrator/tests/compensation-durable.test.js',
        '<rootDir>/core/administrator/tests/display.test.js',
        '<rootDir>/router/tests/keypair.test.js',
        '<rootDir>/sample/tests/basic.test.js',
        '<rootDir>/sample/tests/item.test.js',
        '<rootDir>/core/administrator/tests/returns-contract.test.js',
        '<rootDir>/core/agent/tests/returns-contract.test.js',
        '<rootDir>/core/gateway/tests/returns-contract.test.js',
        '<rootDir>/core/ingress/tests/returns-contract.test.js',
        '<rootDir>/core/ingress/tests/ingest.test.js',
        '<rootDir>/core/mcp/tests/tools.test.js',
        '<rootDir>/core/nexus/tests/returns-contract.test.js',
        '<rootDir>/core/notification/tests/returns-contract.test.js',
        '<rootDir>/apps/fulfillment/tests/returns-contract.test.js',
        '<rootDir>/apps/market/tests/returns-contract.test.js',
        '<rootDir>/apps/market/tests/logic.test.js',
        '<rootDir>/apps/planner/tests/returns-contract.test.js',
        // fleet-standard guide 机制 (2026-07-23, docs/feedback/ai-agent-self-describing-api.md)
        '<rootDir>/library/tests/guide.test.js',
        // system.report 闭环增强：去重计数 + triage 状态 (2026-07-23)
        '<rootDir>/router/tests/report.test.js',
    ],
};
